server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.168.110:9092
    consumer:
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
      bootstrap-servers: 192.168.168.110:9092
